spring:
  cache:
    type: redis
  application:
    name: ddframe
  redis:
    database: 1  
    host: 127.0.0.1
    port: 6379  
    password:   
    pool:
      max-active: 8  
      max-wait: -1  
      max-idle: 8  
      min-idle: 0  
    timeout: 1000