ruiyun:
  base_path: d:/logs
  
default:
    url: jdbc:mysql://127.0.0.1:3306/report?characterEncoding=UTF-8
    username: ruiyun_report
    password: Ruiyun@zzbitem
    driver-class-name: com.mysql.jdbc.Driver
schema:
    #url: jdbc:mysql://106.14.40.221:60001/information_schema?characterEncoding=UTF-8
    url: jdbc:mysql://127.0.0.1:3306/information_schema?characterEncoding=UTF-8
    username: ruiyun_report
    password: Ruiyun@zzbitem
    driver-class-name: com.mysql.jdbc.Driver
    
db1:
    url: jdbc:mysql://127.0.0.1:3306/report?characterEncoding=UTF-8
    username: ruiyun_report
    password: Ruiyun@zzbitem
    driver-class-name: com.mysql.jdbc.Driver
db2:
    url: jdbc:mysql://127.0.0.1:3306/report?characterEncoding=UTF-8
    username: ruiyun_report
    password: Ruiyun@zzbitem
    driver-class-name: com.mysql.jdbc.Driver
db3:
    url: jdbc:mysql://127.0.0.1:3306/report?characterEncoding=UTF-8
    username: ruiyun_report
    password: Ruiyun@zzbitem
    driver-class-name: com.mysql.jdbc.Driver